name: Run PHP and Display HTML

on: [push, pull_request]

jobs:
  run-php:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # Vous pouvez changer la version PHP selon vos besoins

    - name: Start PHP server
      run: php -S localhost:65530 -t vues &

    - name: Wait for server to start
      run: sleep 200  # Augmentez la durée d'attente pour garantir que le serveur démarre

    - name: Curl HTML pages
      run: |
        for file in vues/*.php; do
          curl http://localhost:65530/$(basename $file)
        done
