name: Run PHP and Display HTML

on: [push, pull_request]

jobs:
  run-php:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'  # You can change the PHP version as needed

    - name: Start PHP server
      run: php -S localhost:8000 -t chemin/vers/dossier &

    - name: Wait for server to start
      run: sleep 30  # Increase the sleep duration to ensure the server starts

    - name: Curl HTML pages
      run: |
        for file in /workspaces/RestaurantErythreen/Restaurant/*.php; do
          curl http://localhost:8000/$(basename $file)
        done
